modLoader = "javafml"
loaderVersion = "${forge_compatibility_range}"
issueTrackerURL = "https://github.com/CloudG360/BridgingMod/issues"
license = "MIT"

[[mods]]
modId = "bridgingmod"
version = "${version}"
displayName = "Bridging Mod"
authors = "CG360"
description = "Adds bridging assist similar to Bedrock & Quark's building mechanics."
logoFile = "icon.png"
displayURL = "https://github.com/CloudG360/BridgingMod"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.bridgingmod]]
modId = "forge"
mandatory = true
versionRange = "${forge_compatibility_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bridgingmod]]
modId = "minecraft"
mandatory = true
versionRange = "${supported_minecraft_versions_forge}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bridgingmod]]
modId = "cloth_config"
mandatory = true
versionRange = "[${clothconfig_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.bridgingmod]]
modId = "dynamiccrosshair"
mandatory = false
versionRange = "[${dynamiccrosshair_version},)"
ordering = "AFTER"
side = "CLIENT"